import { saveToken } from './tokenStorage';

const STATIC_TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtaXQuYmlzd2FzMTk5MjAyQGdtYWlsLmNvbSIsImlkIjoiNjY2Njk2N2QtMGQ1NC00Y2VkLWJhZDQtNjYyYThlMTEzNDkyIiwidXNlcm5hbWUiOiJhbWl0LmJpc3dhczE5OTIwMkBnbWFpbC5jb20iLCJyb2xlcyI6WyJTVFVERU5UIiwiQURNSU4iXSwicGVybWlzc2lvbnMiOlsiY291cnNlczp2aWV3IiwiY291cnNlczpjcmVhdGUiLCJjb3Vyc2VzOmVkaXQiLCJjb3Vyc2VzOmRlbGV0ZSIsImV4YW1zOnZpZXciLCJleGFtczpjcmVhdGUiLCJleGFtczplZGl0IiwiZXhhbXM6ZGVsZXRlIiwiZXhhbXM6ZXZhbHVhdGUiLCJxdWVzdGlvbnM6dmlldyIsInF1ZXN0aW9uczpjcmVhdGUiLCJxdWVzdGlvbnM6ZWRpdCIsInF1ZXN0aW9uczpkZWxldGUiLCJjbGFzc2VzOnZpZXciLCJjbGFzc2VzOmNyZWF0ZSIsImNsYXNzZXM6ZWRpdCIsImNsYXNzZXM6ZGVsZXRlIiwiYWNhZGVtaWM6dmlldyIsImFjYWRlbWljOmVkaXQiLCJhZG1pc3Npb246dmlldyIsImFkbWlzc2lvbjplZGl0IiwiYmxvZzp2aWV3IiwiYmxvZzpjcmVhdGUiLCJibG9nOmVkaXQiLCJibG9nOmRlbGV0ZSIsImVib29rczp2aWV3IiwiZWJvb2tzOmNyZWF0ZSIsImVib29rczplZGl0IiwiZWJvb2tzOmRlbGV0ZSIsInBheW1lbnRzOnZpZXciLCJwYXltZW50czplZGl0IiwicGF5bWVudHM6ZGVsZXRlIiwic3ViamVjdHM6dmlldyIsInN1YmplY3RzOmNyZWF0ZSIsInN1YmplY3RzOmVkaXQiLCJzdWJqZWN0czpkZWxldGUiLCJjaGFwdGVyczp2aWV3IiwiY2hhcHRlcnM6Y3JlYXRlIiwiY2hhcHRlcnM6ZWRpdCIsImNoYXB0ZXJzOmRlbGV0ZSIsInVzZXJzOnZpZXciLCJ1c2VyczpjcmVhdGUiLCJ1c2VyczplZGl0IiwidXNlcnM6ZGVsZXRlIiwicm9sZXM6dmlldyIsInJvbGVzOmNyZWF0ZSIsInJvbGVzOmVkaXQiLCJyb2xlczpkZWxldGUiLCJzeXN0ZW06c2V0dGluZ3MiLCJhbmFseXRpY3M6dmlldyJdLCJpYXQiOjE3NTU2Nzk5MjEsImV4cCI6MTc2MzQ1NTkyMX0.3-bod7NJ6Jx4_AqnGrqC_XDFaipkVzVKu4yVWx-BwR0';

export async function initializeStaticToken() {
  try {
    await saveToken('accessToken', STATIC_TOKEN);
    console.log('Static token initialized successfully');
  } catch (error) {
    console.error('Failed to initialize static token:', error);
  }
}
